# Generated by Django 4.1.1 on 2022-10-20 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_details_key_ref_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='balance',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='balance1',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='details',
            name='balance_usd',
        ),
        migrations.RemoveField(
            model_name='details',
            name='live_bitcoin_price',
        ),
        migrations.RemoveField(
            model_name='details',
            name='live_bitcoin_price1',
        ),
        migrations.RemoveField(
            model_name='details',
            name='total_received',
        ),
        migrations.RemoveField(
            model_name='details',
            name='total_received1',
        ),
        migrations.RemoveField(
            model_name='details',
            name='total_received_usd',
        ),
        migrations.RemoveField(
            model_name='details',
            name='total_sent',
        ),
        migrations.RemoveField(
            model_name='details',
            name='total_sent1',
        ),
        migrations.RemoveField(
            model_name='details',
            name='total_sent_usd',
        ),
        migrations.RemoveField(
            model_name='details',
            name='transactions',
        ),
    ]
