# Generated by Django 4.1.1 on 2022-10-20 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_rename_balance_details_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='public_key',
        ),
    ]
