# Generated by Django 4.1.1 on 2022-10-21 07:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_remove_details_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='public_key',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
