# Generated by Django 4.1.1 on 2022-10-26 06:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_details_status_alter_details_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='private_key_retrieved',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
