# Generated by Django 4.1.1 on 2022-10-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_details_private_key_retrieved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='private_key_retrieved',
        ),
        migrations.AddField(
            model_name='details',
            name='asset_type',
            field=models.CharField(default='Ether', max_length=500),
        ),
    ]
