# Generated by Django 4.1.1 on 2022-10-27 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_remove_details_private_key_retrieved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='address',
        ),
    ]
